"""Added years of a department

Revision ID: 1b5dec2ad5aa
Revises: 8941e0dbb1ef
Create Date: 2018-09-04 08:07:48.097051

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1b5dec2ad5aa'
down_revision = '8941e0dbb1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmes', sa.Column('years', sa.Integer(), nullable=False, default=4))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programmes', 'years')
    # ### end Alembic commands ###
