"""create new table users

Revision ID: 31c8d6cf4739
Revises: 6d28c3f63bb8
Create Date: 2017-09-05 12:44:20.970853

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '31c8d6cf4739'
down_revision = '6d28c3f63bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.add_column('lecturers', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lecturers', 'users', ['user'], ['user_id'])
    op.add_column('students', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['user'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'user')
    op.drop_constraint(None, 'lecturers', type_='foreignkey')
    op.drop_column('lecturers', 'user')
    op.drop_table('users')
    # ### end Alembic commands ###
