"""change on primary join

Revision ID: 587a02a3d968
Revises: d42959eef8d4
Create Date: 2017-09-01 01:57:06.427214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587a02a3d968'
down_revision = 'd42959eef8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
