"""new fields in students and lecturers tables

Revision ID: 5cecaf75af73
Revises: 698c699453d7
Create Date: 2017-08-31 20:30:38.345359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cecaf75af73'
down_revision = '698c699453d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('is_lecturer', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('is_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_student')
    op.drop_column('lecturers', 'is_lecturer')
    # ### end Alembic commands ###
