"""mapping of relationship between students and courses

Revision ID: 6748113c1867
Revises: 587a02a3d968
Create Date: 2017-09-02 00:02:48.245340

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6748113c1867'
down_revision = '587a02a3d968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.String(45), nullable=False),
                    sa.Column('courses_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['student_id'], ['students.reg_num'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'student_id', 'courses_id')
                    )
    op.create_index(op.f('ix_student_courses_courses_id'), 'student_courses', ['courses_id'], unique=False)
    op.create_index(op.f('ix_student_courses_student_id'), 'student_courses', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_courses_student_id'), table_name='student_courses')
    op.drop_index(op.f('ix_student_courses_courses_id'), table_name='student_courses')
    op.drop_table('student_courses')
    # ### end Alembic commands ###
