"""drop id field

Revision ID: 698c699453d7
Revises: d6a8269736ed
Create Date: 2017-08-22 13:31:58.526911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698c699453d7'
down_revision = 'd6a8269736ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
