"""remove NOT NULL constraint

Revision ID: 882074fb4391
Revises: 31c8d6cf4739
Create Date: 2017-09-19 03:06:02.855369

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '882074fb4391'
down_revision = '31c8d6cf4739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'verified',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'verified',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    # ### end Alembic commands ###
