"""Create new database

Revision ID: 8941e0dbb1ef
Revises: 
Create Date: 2018-07-16 10:23:47.998834

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import FetchedValue

revision = '8941e0dbb1ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_of_the_week',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=10), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('extras',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source', sa.String(length=120), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('altitude', sa.Float(), nullable=True),
                    sa.Column('LAC', sa.Float(), nullable=True),
                    sa.Column('CID', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('programmes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('program_id', sa.String(length=8), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('program_id')
                    )
    op.create_table('suggestions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=20), nullable=False),
                    sa.Column('message', sa.String(length=2000), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('verification_statuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(length=40), nullable=False),
                    sa.Column('error_message', sa.String(length=140), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('programme_id', sa.String(length=8), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.ForeignKeyConstraint(['programme_id'], ['programmes.program_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_courses_programme_id'), 'courses', ['programme_id'], unique=False)
    op.create_table('lecturers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('staff_id', sa.String(length=15), nullable=False),
                    sa.Column('name', sa.String(length=45), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('rank', sa.String(length=25), nullable=True),
                    sa.Column('programme', sa.String(length=80), nullable=True),
                    sa.Column('is_lecturer', sa.Boolean(), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('user', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['programme'], ['programmes.name'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('staff_id')
                    )
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('reg_num', sa.String(length=45), nullable=True),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('year_of_study', sa.Integer(), nullable=False),
                    sa.Column('programme', sa.String(length=80), nullable=False),
                    sa.Column('class_rep', sa.Boolean(), nullable=False),
                    sa.Column('is_student', sa.Boolean(), nullable=True),
                    sa.Column('user', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['programme'], ['programmes.name'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_students_class_rep'), 'students', ['class_rep'], unique=False)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_reg_num'), 'students', ['reg_num'], unique=True)
    op.create_index(op.f('ix_students_year_of_study'), 'students', ['year_of_study'], unique=False)
    op.create_table('lecturers_teaching',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lecturers_id', sa.Integer(), nullable=False),
                    sa.Column('courses_id', sa.Integer(), nullable=False),
                    sa.Column('programme', sa.String(length=8), nullable=False),
                    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['lecturers_id'], ['lecturers.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['programme'], ['programmes.program_id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'lecturers_id', 'courses_id')
                    )
    op.create_index(op.f('ix_lecturers_teaching_courses_id'), 'lecturers_teaching', ['courses_id'], unique=False)
    op.create_index(op.f('ix_lecturers_teaching_lecturers_id'), 'lecturers_teaching', ['lecturers_id'], unique=False)
    op.create_table('photos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.String(length=45), nullable=False),
                    sa.Column('address', sa.String(length=100), nullable=False),
                    sa.Column('learning', sa.Boolean(), server_default=FetchedValue(), nullable=False),
                    sa.ForeignKeyConstraint(['student_id'], ['students.reg_num'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('address')
                    )
    op.create_index(op.f('ix_photos_student_id'), 'photos', ['student_id'], unique=False)
    op.create_table('student_courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.String(length=45), nullable=False),
                    sa.Column('courses_id', sa.Integer(), nullable=False),
                    sa.Column('programme', sa.String(length=8), nullable=False),
                    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['programme'], ['programmes.program_id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['student_id'], ['students.reg_num'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'student_id', 'courses_id')
                    )
    op.create_index(op.f('ix_student_courses_courses_id'), 'student_courses', ['courses_id'], unique=False)
    op.create_index(op.f('ix_student_courses_student_id'), 'student_courses', ['student_id'], unique=False)
    op.create_table('classes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_started', sa.DateTime(), nullable=False),
                    sa.Column('duration', sa.Float(), server_default=FetchedValue(), nullable=False),
                    sa.Column('archived', sa.Boolean(), server_default=FetchedValue(), nullable=False),
                    sa.Column('lec_course_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['lec_course_id'], ['lecturers_teaching.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_classes_lec_course_id'), 'classes', ['lec_course_id'], unique=False)
    op.create_index(op.f('ix_classes_time_started'), 'classes', ['time_started'], unique=False)
    op.create_table('attendance',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student', sa.String(length=45), nullable=False),
                    sa.Column('class_', sa.Integer(), nullable=False),
                    sa.Column('verified', sa.Integer(), nullable=True),
                    sa.Column('uploaded_photo', sa.String(length=100), nullable=False),
                    sa.Column('course', sa.String(length=80), nullable=True),
                    sa.Column('time_started', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['class_'], ['classes.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['course'], ['courses.name'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['student'], ['students.reg_num'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['uploaded_photo'], ['photos.address'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['verified'], ['verification_statuses.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'student', 'class_', 'uploaded_photo')
                    )
    op.create_index(op.f('ix_attendance_time_started'), 'attendance', ['time_started'], unique=False)
    op.create_index(op.f('ix_attendance_verified'), 'attendance', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_verified'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_time_started'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_classes_time_started'), table_name='classes')
    op.drop_index(op.f('ix_classes_lec_course_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_student_courses_student_id'), table_name='student_courses')
    op.drop_index(op.f('ix_student_courses_courses_id'), table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_photos_student_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_lecturers_teaching_lecturers_id'), table_name='lecturers_teaching')
    op.drop_index(op.f('ix_lecturers_teaching_courses_id'), table_name='lecturers_teaching')
    op.drop_table('lecturers_teaching')
    op.drop_index(op.f('ix_students_year_of_study'), table_name='students')
    op.drop_index(op.f('ix_students_reg_num'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_class_rep'), table_name='students')
    op.drop_table('students')
    op.drop_table('lecturers')
    op.drop_index(op.f('ix_courses_programme_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('verification_statuses')
    op.drop_table('users')
    op.drop_table('suggestions')
    op.drop_table('programmes')
    op.drop_table('extras')
    op.drop_table('days_of_the_week')
    # ### end Alembic commands ###
