"""Added student email confirmation

Revision ID: b28095ca56f0
Revises: eb406bfd44b8
Create Date: 2018-12-25 19:23:05.862561

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b28095ca56f0'
down_revision = 'eb406bfd44b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email_confirmed')
    # ### end Alembic commands ###
