"""modified attendance

Revision ID: bc793a9bc5e7
Revises: 04a84768a546
Create Date: 2017-09-25 20:37:10.412732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc793a9bc5e7'
down_revision = '04a84768a546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('course', sa.String(length=80), nullable=True))
    op.add_column('attendance', sa.Column('time_started', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_attendance_time_started'), 'attendance', ['time_started'], unique=False)
    op.create_foreign_key(None, 'attendance', 'courses', ['course'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_time_started'), table_name='attendance')
    op.drop_column('attendance', 'time_started')
    op.drop_column('attendance', 'course')
    # ### end Alembic commands ###
