"""changing foreign key reference in students

Revision ID: d42959eef8d4
Revises: 5cecaf75af73
Create Date: 2017-09-01 01:44:54.273882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42959eef8d4'
down_revision = '5cecaf75af73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_ibfk_1', 'students', type_='foreignkey')
    op.create_foreign_key('students_ibfk_1', 'students', 'programmes', ['programme'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_ibfk_1', 'students', type_='foreignkey')
    op.create_foreign_key('students_ibfk_1', 'students', 'programmes', ['programme'], ['program_id'])
    # ### end Alembic commands ###
