"""create days table

Revision ID: d6a8269736ed
Revises: 1a45e87a0390
Create Date: 2017-08-21 13:45:32.283635

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd6a8269736ed'
down_revision = '1a45e87a0390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_of_the_week',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=10), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_of_the_week')
    # ### end Alembic commands ###
