"""Added staff email confirmation

Revision ID: eb406bfd44b8
Revises: 1b5dec2ad5aa
Create Date: 2018-12-24 15:18:20.504685

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eb406bfd44b8'
down_revision = '1b5dec2ad5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturers', 'email_confirmed')
    # ### end Alembic commands ###
