"""create suggestions and extras tables

Revision ID: f4a8ef2b6155
Revises: 882074fb4391
Create Date: 2017-09-21 21:14:57.428452

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4a8ef2b6155'
down_revision = '882074fb4391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extras',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source', sa.String(length=120), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('LAC', sa.Float(), nullable=True),
                    sa.Column('CID', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('suggestions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=20), nullable=False),
                    sa.Column('message', sa.String(length=2000), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    op.drop_table('extras')
    # ### end Alembic commands ###
